name: Publish to WinGet

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Publish Getsu to WinGet Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: skttr87.getsu
          installer-type: inno
          token: ${{ secrets.WINGET_TOKEN }}
